---
- name: Include Cloudflare domain and zone IDs variables
  ansible.builtin.include_vars:
    file: "vars/cloudflare_vars.yml"

- name: Debug cloudflare_zone_ids variable content
  ansible.builtin.debug:
    var: cloudflare_zone_ids

- name: Install Coolify
  become: true
  shell: curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash
  args:
    executable: /bin/bash
